### ISSUE TITLE
Paper/Citation Available?

### ISSUE THREAD

**Issue by TiagoFilipeSousaGoncalves** [B-cos/B-cos-v2#2]
Hi,

Our group is working with this model and, potentially, preparing a publication/paper. Do you have the original article (or citation) for the B-cos-v2 so we can cite your work?

Thank you.

Best,
Tiago

**Comment by moboehle** [comment]
Hi Tiago,

Thanks for your interest in our work on the B-cos networks! For the submission, please cite the GitHub repository for now, we will release the corresponding paper shortly. Once it is available, we would be grateful if you could update the submission accordingly.

I will keep you posted!

Best,
Moritz

**Comment by TiagoFilipeSousaGoncalves** [comment]
Thank you! :)

**Comment by moboehle** [comment]
Hi Tiago, sorry for the delay, the paper is finally available here: [B-cos Alignment for Inherently Interpretable CNNs and Vision Transformers](https://arxiv.org/abs/2306.10898)
