### ISSUE TITLE
About obtaining explanations of the models

### ISSUE THREAD

**Issue by tulilin** [B-cos/B-cos-v2#6]
Hello, I really appreciate your wonderful work and I have read the code. To obtain the explanations of the models, according to the code (model.explain()), it seems that the contribution maps were calculated in the same way as the IxG post-hoc explanation method, and I have two questions here:
(1) As mentioned in the paper, the dynamic linear weights W(x) in y(x) = W(x)x (or W_(1->L) in this paper) were visualized to obtain explanations. And as I understand, in the code, the gradient of the input was regarded as the dynamic linear weights. Why are these two equivalent?
(2) For rows 1+2 of Fig. 6 in the paper, the results of "IxG" and "Ours" are different, and "Ours" are obviously better. What is the difference between the implementation of model.explain() in the code and "IxG"? By the way, what is the target layer for visualization of GradCAM in Fig. 6?
I am looking forward to your reply. Thank you very much!

**Comment by moboehle** [comment]
Hi, 

Thanks a lot for your message and your interest! To obtain the explanations, we indeed rely on the model's backward pass (i.e. the gradient). Note, however, that the gradient is modified: specifically, the "dynamic weights" w(x) are detached from the computational graph in every layer when the model is in explanation mode ([see code](https://github.com/B-cos/B-cos-v2/blob/main/bcos/modules/bcosconv2d.py#L167)). This treats the weights w(x) as input-independent as far as the gradient is concerned, and the gradient computation thus returns the weight matrix w. This also explains the difference you observed in the model explanations between IxG and Ours.

I hope this answers the question! If not, let me know :) 

Cheers
Moritz

**Comment by tulilin** [comment]
> Hi,
> 
> Thanks a lot for your message and your interest! To obtain the explanations, we indeed rely on the model's backward pass (i.e. the gradient). Note, however, that the gradient is modified: specifically, the "dynamic weights" w(x) are detached from the computational graph in every layer when the model is in explanation mode ([see code](https://github.com/B-cos/B-cos-v2/blob/main/bcos/modules/bcosconv2d.py#L167)). This treats the weights w(x) as input-independent as far as the gradient is concerned, and the gradient computation thus returns the weight matrix w. This also explains the difference you observed in the model explanations between IxG and Ours.
> 
> I hope this answers the question! If not, let me know :)
> 
> Cheers Moritz

Got it, Thank you very much!
